services:
  postgres:
    image: 'postgres:18.0-alpine'
    environment:
      - 'POSTGRES_DB=coupon'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
  lgtm:
    image: grafana/otel-lgtm:0.11.14
    ports:
      - '4317:4317'
      - '4318:4318'
      - '3000:3000'
      - '9090:9090'
