server:
  shutdown: graceful

spring:
  application:
    name: coupon
  datasource:
    url: jdbc:postgresql://localhost:5432/coupon
    username: myuser
    password: secret
  docker:
    compose:
      enabled: true
      file: ./compose-local.yaml

  threads:
    virtual:
      enabled: true

  sql:
    init:
      mode: always # Please note that this is for development only
  mvc:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,prometheus"
logging:
  level:
    dev.tpcoder.coupon: debug
